name: SimplyUHC
main: com.codeski.simplyuhc.SimplyUHC
version: @version@
commands:
  uhc:
    description: Stop or start an Ultra Hardcore game
    usage: /uhc \<command\> [arguments]
    permission: simplyuhc.op
    permission-message: You do not have permission.
